USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE DEV_DIGITAL_DROPS;
/*************************************************************
*
*	DDL: CONTROL TABLES
*
*************************************************************/
CREATE OR REPLACE SCHEMA DEV_DIGITAL_DROPS.CONTROL;

CREATE OR REPLACE SEQUENCE DEV_DIGITAL_DROPS.CONTROL.JOB_SUMMARY_SK START 1 INCREMENT 1;

CREATE OR REPLACE TABLE DEV_DIGITAL_DROPS.CONTROL.JOB_SUMMARY
					(
					      JOB_SUMMARY_SK NUMBER(38,0) DEFAULT DEV_DIGITAL_DROPS.CONTROL.JOB_SUMMARY_SK.NEXTVAL NOT NULL
						,JOB_SUMMARY_START_TIMESTAMP_UTC TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC',CURRENT_TIMESTAMP)::TIMESTAMP_NTZ NOT NULL
						,JOB_SUMMARY_END_TIMESTAMP_UTC TIMESTAMP_NTZ
						,JOB_SUMMARY_STATUS VARCHAR DEFAULT 'RUNNING'
						,JOB_SUMMARY_EXCEPTION VARCHAR
					);

-- CREATE OR REPLACE TABLE DEV_DIGITAL_DROPS.CONTROL.JOB_DETAIL;
/*************************************************************
*
*	DDL: STAGING TABLES
*
*************************************************************/
CREATE OR REPLACE SCHEMA DEV_DIGITAL_DROPS.STAGING;

CREATE OR REPLACE SEQUENCE DEV_DIGITAL_DROPS.STAGING.REQUEST_SK START 1 INCREMENT 1;

CREATE OR REPLACE TABLE DEV_DIGITAL_DROPS.STAGING.REQUEST
                        (
                              REQUEST_SK NUMBER(38,0) DEFAULT DEV_DIGITAL_DROPS.STAGING.REQUEST_SK.NEXTVAL NOT NULL
                              ,REQUEST_ENDPOINT VARCHAR NOT NULL
						,REQUEST_RESPONSE VARIANT NOT NULL
						,META_PAGE_NUMBER NUMBER(38,0) DEFAULT 1
                        		,META_JOB_SUMMARY_SK NUMBER(38,0) NOT NULL
						,META_LOAD_TIMESTAMP_UTC TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC',CURRENT_TIMESTAMP)::TIMESTAMP_NTZ NOT NULL
                        );
/*************************************************************
*
*	DDL: MODEL TABLES
*
*************************************************************/
CREATE OR REPLACE SCHEMA DEV_DIGITAL_DROPS.MODEL;

CREATE OR REPLACE SEQUENCE DEV_DIGITAL_DROPS.MODEL.FILM_SK START 1 INCREMENT 1;

CREATE OR REPLACE TABLE DEV_DIGITAL_DROPS.MODEL.FILM
     				(
     				     FILM_SK NUMBER(38,0) DEFAULT DEV_DIGITAL_DROPS.MODEL.FILM_SK.NEXTVAL NOT NULL
     					,FILM_ID NUMBER(38,0)
     					,FILM_ORIGINAL_LANGUAGE VARCHAR
     					,FILM_ORIGINAL_TITLE VARCHAR
     					,FILM_OVERVIEW VARCHAR
     					,FILM_POPULARITY NUMBER
     					,FILM_POSTER_PATH VARCHAR
     					,FILM_RELEASE_DATE DATE
     					,FILM_TITLE VARCHAR
     					,FILM_VIDEO BOOLEAN
     					,FILM_VOTE_AVERAGE NUMBER
     					,FILM_VOTE_COUNT NUMBER
     					,META_REQUEST_SK NUMBER(38,0) NOT NULL
     					,META_JOB_SUMMARY_SK NUMBER(38,0) NOT NULL
     					,META_LOAD_TIMESTAMP_UTC TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC',CURRENT_TIMESTAMP)::TIMESTAMP_NTZ NOT NULL
					);
/*************************************************************
*
*	DCL: SECURITY
*
*************************************************************/
USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_API;
GRANT USAGE ON DATABASE DEV_DIGITAL_DROPS TO ROLE ROLE_API;

GRANT USAGE ON SCHEMA DEV_DIGITAL_DROPS.CONTROL TO ROLE ROLE_API;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA DEV_DIGITAL_DROPS.CONTROL TO ROLE ROLE_API;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA DEV_DIGITAL_DROPS.CONTROL TO ROLE ROLE_API;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA DEV_DIGITAL_DROPS.CONTROL TO ROLE ROLE_API;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA DEV_DIGITAL_DROPS.CONTROL TO ROLE ROLE_API;

GRANT USAGE ON SCHEMA DEV_DIGITAL_DROPS.STAGING TO ROLE ROLE_API;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA DEV_DIGITAL_DROPS.STAGING TO ROLE ROLE_API;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA DEV_DIGITAL_DROPS.STAGING TO ROLE ROLE_API;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA DEV_DIGITAL_DROPS.STAGING TO ROLE ROLE_API;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA DEV_DIGITAL_DROPS.STAGING TO ROLE ROLE_API;

GRANT USAGE ON SCHEMA DEV_DIGITAL_DROPS.MODEL TO ROLE ROLE_API;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA DEV_DIGITAL_DROPS.MODEL TO ROLE ROLE_API;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA DEV_DIGITAL_DROPS.MODEL TO ROLE ROLE_API;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA DEV_DIGITAL_DROPS.MODEL TO ROLE ROLE_API;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA DEV_DIGITAL_DROPS.MODEL TO ROLE ROLE_API;

USE ROLE ROLE_API;
