USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE DEV_DIGITAL_DROPS;
/*************************************************************
*
*	DDL: CONTROL TABLES
*
*************************************************************/
CREATE OR REPLACE SCHEMA DEV_DIGITAL_DROPS.CONTROL;

CREATE OR REPLACE SEQUENCE DEV_DIGITAL_DROPS.CONTROL.JOB_SUMMARY_SK START 1 INCREMENT 1;

CREATE OR REPLACE TABLE DEV_DIGITAL_DROPS.CONTROL.JOB_SUMMARY
(
    JOB_SUMMARY_SK                  NUMBER(38, 0) DEFAULT DEV_DIGITAL_DROPS.CONTROL.JOB_SUMMARY_SK.NEXTVAL          NOT NULL,
    JOB_SUMMARY_START_TIMESTAMP_UTC TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ NOT NULL,
    JOB_SUMMARY_END_TIMESTAMP_UTC   TIMESTAMP_NTZ,
    JOB_SUMMARY_STATUS              VARCHAR       DEFAULT 'RUNNING',
    JOB_SUMMARY_EXCEPTION           VARCHAR
);

-- CREATE OR REPLACE TABLE DEV_DIGITAL_DROPS.CONTROL.JOB_DETAIL;
/*************************************************************
*
*	DDL: STAGING TABLES
*
*************************************************************/
CREATE OR REPLACE SCHEMA DEV_DIGITAL_DROPS.STAGING;

CREATE OR REPLACE SEQUENCE DEV_DIGITAL_DROPS.STAGING.REQUEST_SK START 1 INCREMENT 1;

-- TODO: ADD REQUEST_SOURCE, etc.

CREATE OR REPLACE TABLE DEV_DIGITAL_DROPS.STAGING.REQUEST
(
    REQUEST_SK                NUMBER(38, 0) DEFAULT DEV_DIGITAL_DROPS.STAGING.REQUEST_SK.NEXTVAL              NOT NULL,
    REQUEST_PROVIDER          VARCHAR                                                                         NOT NULL,
    REQUEST_ENDPOINT          VARCHAR                                                                         NOT NULL,
    REQUEST_RESPONSE          VARIANT                                                                         NOT NULL,
    META_PAGE_NUMBER          NUMBER(38, 0) DEFAULT 1                                                         NOT NULL,
    META_JOB_SUMMARY_SK       NUMBER(38, 0)                                                                   NOT NULL,
    META_INSERT_TIMESTAMP_UTC TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ NOT NULL,
    META_CURRENT_INDICATOR    BOOLEAN                                                                         NOT NULL DEFAULT FALSE
);
/*************************************************************
*
*	DDL: MODEL TABLES
*
*************************************************************/
CREATE OR REPLACE SCHEMA DEV_DIGITAL_DROPS.MODEL;

CREATE OR REPLACE SEQUENCE DEV_DIGITAL_DROPS.MODEL.FILM_SK START 1 INCREMENT 1;
CREATE OR REPLACE SEQUENCE DEV_DIGITAL_DROPS.MODEL.GAME_SK START 1 INCREMENT 1;

CREATE OR REPLACE TABLE DEV_DIGITAL_DROPS.MODEL.GAME
(
    GAME_SK                      NUMBER(38, 0) DEFAULT DEV_DIGITAL_DROPS.MODEL.GAME_SK.NEXTVAL                   NOT NULL,
    GAME_AGE_RATINGS             ARRAY,
    GAME_AGGREGATED_RATING       NUMBER(38,15),
    GAME_AGGREGATED_RATING_COUNT NUMBER(38,0),
    GAME_ALTERNATIVE_NAMES       ARRAY,
    GAME_ARTWORKS                ARRAY,
    GAME_BUNDLES                 ARRAY,
    GAME_CATEGORY                VARCHAR,
    GAME_COLLECTION              VARCHAR,
    GAME_COVER                   VARCHAR,
    GAME_CREATED_AT              TIMESTAMP_NTZ,
    GAME_DLCS                    ARRAY,
    GAME_EXPANSIONS              ARRAY,
    GAME_EXTERNAL_GAMES          ARRAY,
    GAME_FIRST_RELEASE_DATE      TIMESTAMP_NTZ,
    GAME_FOLLOWS                 NUMBER(38,0),
    GAME_FRANCHISE               VARCHAR,
    GAME_FRANCHISES              ARRAY,
    GAME_GAME_ENGINES            ARRAY,
    GAME_GAME_MODES              ARRAY,
    GAME_GENRES                  ARRAY,
    GAME_HYPES                   NUMBER(38,0),
    GAME_ID                      NUMBER(38,0),
    GAME_INVOLVED_COMPANIES      ARRAY,
    GAME_KEYWORDS                ARRAY,
    GAME_MULTIPLAYER_MODES       ARRAY,
    GAME_NAME                    VARCHAR,
    GAME_PARENT_GAME             VARCHAR,
    GAME_PLATFORMS               ARRAY,
    GAME_PLAYER_PERSPECTIVES     ARRAY,
    GAME_POPULARITY              NUMBER(38,15),
    GAME_PULSE_COUNT             NUMBER(38,0),
    GAME_RATING                  NUMBER(38,15),
    GAME_RATING_COUNT            NUMBER(38,0),
    GAME_RELEASE_DATES           ARRAY,
    GAME_SCREENSHOTS             ARRAY,
    GAME_SIMILAR_GAMES           ARRAY,
    GAME_SLUG                    VARCHAR,
    GAME_STANDALONE_EXPANSIONS   ARRAY,
    GAME_STATUS                  VARCHAR,
    GAME_STORYLINE               VARCHAR,
    GAME_SUMMARY                 VARCHAR,
    GAME_TAGS                    ARRAY,
    GAME_THEMES                  ARRAY,
    GAME_TIME_TO_BEAT            VARCHAR,
    GAME_TOTAL_RATING            NUMBER(38,15),
    GAME_TOTAL_RATING_COUNT      NUMBER(38,0),
    GAME_UPDATED_AT              TIMESTAMP_NTZ,
    GAME_URL                     VARCHAR,
    GAME_VERSION_PARENT          NUMBER(38,0),
    GAME_VERSION_TITLE           VARCHAR,
    GAME_VIDEOS                  ARRAY,
    GAME_WEBSITES                ARRAY,
    META_REQUEST_SK              NUMBER(38, 0)                                                                   NOT NULL,
    META_JOB_SUMMARY_SK          NUMBER(38, 0)                                                                   NOT NULL,
    META_INSERT_TIMESTAMP_UTC    TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ NOT NULL,
    META_UPDATE_TIMESTAMP_UTC    TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ NOT NULL,
    META_DELETE_TIMESTAMP_UTC    TIMESTAMP_NTZ
);

CREATE OR REPLACE TABLE DEV_DIGITAL_DROPS.MODEL.FILM
(
    FILM_SK                   NUMBER(38, 0) DEFAULT DEV_DIGITAL_DROPS.MODEL.FILM_SK.NEXTVAL                   NOT NULL,
    FILM_ADULT                VARCHAR,
    FILM_BACKDROP_PATH        VARCHAR,
    FILM_GENRE_IDS            VARIANT,
    FILM_ID                   VARCHAR,
    FILM_ORIGINAL_LANGUAGE    VARCHAR,
    FILM_ORIGINAL_TITLE       VARCHAR,
    FILM_OVERVIEW             VARCHAR,
    FILM_POPULARITY           VARCHAR,
    FILM_POSTER_PATH          VARCHAR,
    FILM_RELEASE_DATE         VARCHAR,
    FILM_TITLE                VARCHAR,
    FILM_VIDEO                VARCHAR,
    FILM_VOTE_AVERAGE         VARCHAR,
    FILM_VOTE_COUNT           VARCHAR,
    META_REQUEST_SK           NUMBER(38, 0)                                                                   NOT NULL,
    META_JOB_SUMMARY_SK       NUMBER(38, 0)                                                                   NOT NULL,
    META_INSERT_TIMESTAMP_UTC TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ NOT NULL,
    META_UPDATE_TIMESTAMP_UTC TIMESTAMP_NTZ DEFAULT CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP)::TIMESTAMP_NTZ NOT NULL,
    META_DELETE_TIMESTAMP_UTC TIMESTAMP_NTZ
);
/*************************************************************
*
*	DCL: SECURITY
*
*************************************************************/
USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ROLE_API;
GRANT USAGE ON DATABASE DEV_DIGITAL_DROPS TO ROLE ROLE_API;

GRANT USAGE ON SCHEMA DEV_DIGITAL_DROPS.CONTROL TO ROLE ROLE_API;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA DEV_DIGITAL_DROPS.CONTROL TO ROLE ROLE_API;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA DEV_DIGITAL_DROPS.CONTROL TO ROLE ROLE_API;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA DEV_DIGITAL_DROPS.CONTROL TO ROLE ROLE_API;
GRANT INSERT, SELECT ON FUTURE TABLES IN SCHEMA DEV_DIGITAL_DROPS.CONTROL TO ROLE ROLE_API;

GRANT USAGE ON SCHEMA DEV_DIGITAL_DROPS.STAGING TO ROLE ROLE_API;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA DEV_DIGITAL_DROPS.STAGING TO ROLE ROLE_API;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA DEV_DIGITAL_DROPS.STAGING TO ROLE ROLE_API;
GRANT INSERT, SELECT, UPDATE ON ALL TABLES IN SCHEMA DEV_DIGITAL_DROPS.STAGING TO ROLE ROLE_API;
GRANT INSERT, SELECT, UPDATE ON FUTURE TABLES IN SCHEMA DEV_DIGITAL_DROPS.STAGING TO ROLE ROLE_API;

GRANT USAGE ON SCHEMA DEV_DIGITAL_DROPS.MODEL TO ROLE ROLE_API;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA DEV_DIGITAL_DROPS.MODEL TO ROLE ROLE_API;
GRANT USAGE ON FUTURE SEQUENCES IN SCHEMA DEV_DIGITAL_DROPS.MODEL TO ROLE ROLE_API;
GRANT INSERT, SELECT, UPDATE ON ALL TABLES IN SCHEMA DEV_DIGITAL_DROPS.MODEL TO ROLE ROLE_API;
GRANT INSERT, SELECT, UPDATE ON FUTURE TABLES IN SCHEMA DEV_DIGITAL_DROPS.MODEL TO ROLE ROLE_API;

USE ROLE ROLE_API;
